steps:
  - name: 'gcr.io/cloud-builders/go'
    entrypoint: '/bin/sh'
    args:
      - '-c'
      - |
        go test ./test/... -covermode=count -coverprofile=./c.out
        go tool cover -html=c.out -o coverage.html
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        gsutil mv ./coverage.html  gs://${_BUCKET_NAME}/index.html
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: '/bin/bash'
    args:
      - '-c'
      - |
        gcloud app versions list --service=${_SERVICE} | grep ${_SERVICE} | sort -rk 4,4 | awk '{print $2}' | tail -n +${_REMAIN_VERSION_COUNT} | xargs -I {} gcloud app versions delete {}
        cd $_OUTPUT_DIR
        gcloud app deploy  ${_NO_PROMOTE}
substitutions:
  _REMAIN_VERSION_COUNT: "20"
