version: '3.5'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=sample
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb_flush_log_at_trx_commit=2 --innodb_use_native_aio=0 --sync_binlog=0
    volumes:
      - "db-data:/var/lib/mysql"
      - ./docker/mysql/my.conf:/etc/mysql/my.conf
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
volumes:
  db-data:
    driver: local