// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/rikodao/clean-architecture-golang-sample/pkg/adaptor/controller/userController"
	"github.com/rikodao/clean-architecture-golang-sample/pkg/adaptor/presentator/userPresentator"
	"github.com/rikodao/clean-architecture-golang-sample/pkg/adaptor/repository/userRepository"
	"github.com/rikodao/clean-architecture-golang-sample/pkg/application/usecase"
	"github.com/rikodao/clean-architecture-golang-sample/pkg/infrastracture/handler/chi"
	"net/http"
)

// Injectors from wire.go:

func InitializeRouter() (http.Handler, error) {
	userInMemoryRepository, err := userRepository.New()
	if err != nil {
		return nil, err
	}
	userJsonPresentator, err := userPresentator.New()
	if err != nil {
		return nil, err
	}
	getUserInteractor, err := usecase.New(userInMemoryRepository, userJsonPresentator)
	if err != nil {
		return nil, err
	}
	userJsonController, err := userController.New(getUserInteractor)
	if err != nil {
		return nil, err
	}
	handler := chi.NewHandler(userJsonController)
	return handler, nil
}
